language: node_js

node_js: 
  - "20"

cache: 
  directories:
    - node_modules

# branches to build
branches: 
  only:
    - main


install:
  - npm install 

# run script before deploy
script: 
  - npm run lint
  - npm run test
  - npm run build